services:
  html-page:
    build:
      context: .  # Build the HTML page from the Dockerfile
    networks:
      - web-network
    expose:
      - "5003"  # Expose internally on port 5003
    deploy:
      replicas: 3  # Scale to 3 replicas of the HTML page service

  nginx:
    image: nginx:alpine  # Use the official NGINX image
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX config
    ports:
      - "5003:5003"  # Expose port 5003 on the host
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
