version: '3.8'

services:
  web:
    build: .
    expose:
      - "5004"  # Expose the container port (no direct mapping to host port)
      - "5005"  # Expose another container port
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - webnet
    deploy:
      replicas: 2  # Number of web service instances

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5003:5003"  # Expose Nginx on port 5003
    networks:
      - webnet
    depends_on:
      - web

networks:
  webnet:
    driver: bridge
