version: '3.8'

services:
  backend1:
    image: backend1  # Ensure this image exists
    ports:
      - "5004:5004"
    networks:
      - webnet  # Add backend1 to webnet

  backend2:
    image: backend2  # Ensure this image exists
    ports:
      - "5005:5005"
    networks:
      - webnet  # Add backend2 to webnet

  backend3:
    image: backend3  # Ensure this image exists
    ports:
      - "5006:5006"
    networks:
      - webnet  # Add backend3 to webnet

  nginx:
    image: nginx:latest
    ports:
      - "5003:5003"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
