version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
    volumes:
      - .:/usr/share/nginx/html
    container_name: sample3
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
