version: '3.7'

services:
  html-page1:
    build:
      context: .  # Build the HTML page from the Dockerfile in the current directory
    networks:
      - web-network
    expose:
      - "5003"  # Expose port 80 for the NGINX load balancer to access

  html-page2:
    build:
      context: .  # Build the HTML page from the Dockerfile in the current directory
    networks:
      - web-network
    expose:
      - "5003"  # Expose port 80 for the NGINX load balancer to access

  html-page3:
    build:
      context: .  # Build the HTML page from the Dockerfile in the current directory
    networks:
      - web-network
    expose:
      - "5003"  # Expose port 80 for the NGINX load balancer to access  
  nginx:
    image: nginx:alpine  # Use the official NGINX image
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the custom NGINX config
      - /etc/ssl/certs:/etc/ssl/certs         # Mount /etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private 
    ports:
      - "5003:5003"  # Expose port 5003 on the host, forwarding to port 5003 on the container
      - "5003:5003"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
