version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/usr/share/nginx/html
    container_name: sample3
    networks:
      - webnet
    depends_on:
      - backend1
      - backend2

  backend1:
    build:
    context: .
    dockerfile: Dockerfile
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 5s
      timeout: 3s
      retries: 3

  backend2:
    build:
    context: .
    dockerfile: Dockerfile
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  webnet:
    driver: bridge