version: "3.8"

services:
  app1:
    build:
      context: .
    container_name: app1
    networks:
      - app-network

  app2:
    build:
      context: .
    container_name: app2
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app1
      - app2

networks:
  app-network:
    driver: bridge
