version: "3.8"

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    expose:
      - "5003"  # Expose the application port for internal network use
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    expose:
      - "5003"  # Expose the application port for internal network use
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind mount the custom NGINX config file
    ports:
      - "5003:5003"  # Expose port 5003 on the host and forward to port 80 on NGINX
    networks:
      - app-network
    depends_on:
      - app1
      - app2

networks:
  app-network:
    driver: bridge
