version: "3"

services:
  app1:
    build: .
    container_name: app1
    volumes:
      - ./sample3:/sample3
    ports:
      - "5004:5003"
  
  app2:
    build: .
    container_name: app2
    volumes:
      - ./sample3:/sample3
    ports:
      - "5005:5003"

  app3:
    build: .
    container_name: app3
    volumes:
      - ./sample3:/sample3
    ports:
      - "5006:5003"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 5003:5003
    volumes:
      - nginx.conf:/etc/nginx/conf.d/default.conf
