version: "3.8"

services:
  app1:
    build:
      context: .
    container_name: app1
    ports:
      - "5003:5003"  # Expose port 5003 of the container to port 5003 on the host
    networks:
      - app-network

  app2:
    build:
      context: .
    container_name: app2
    ports:
      - "5004:5003"  # Expose port 5003 of the container to port 5003 on the host
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the nginx.conf file into Nginx
    ports:
      - "5003:80"  # Expose port 5003 on the host and forward it to port 80 on Nginx
    networks:
      - app-network
    depends_on:
      - app1
      - app2

networks:
  app-network:
    driver: bridge
