version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    container_name: sample3
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
