version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind mount the custom NGINX config file
    ports:
      - "5003:80"  # Expose port 5003 on the host and forward to port 80 on NGINX
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
