version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/usr/share/nginx/html
    container_name: sample2
    networks:
      - webnet
    depends_on:
      - backend1
      - backend2

  backend1:
    image: backend1
    ports:
      - "5004:5003"
    networks:
      - webnet

  backend2:
    image: backend2
    ports:
      - "5005:5003"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
