version: '3.8'

services:
  # Backend Web Server 1
  web1:
    build:
      context: .
    networks:
      - webnet

  # Backend Web Server 2
  web2:
    build:
      context: .
    networks:
      - webnet

  # Nginx Load Balancer
  nginx:
    image: nginx:latest  # Use the official Nginx image from Docker Hub
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx configuration file
    ports:
      - "5003:5003"  # Expose port 8080 on host to access the load balancer
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
